### PR TITLE
Add hostname to validation cache key for multi-node support.

### PR DESCRIPTION
**Pull request by colinmollenhour**
I believe there is a possibility for a bug in multi-node environments (assuming var directory is not on shared storage). Consider the following:
- Page request to Node1 warms Node1 cache. validationCacheKey is set.
- Page request to Node2 warms Node2 cache (no validIndex).
- Updated layout XML is pushed to both nodes. "layout" cache type is cleared.
- Page request to Node1 updates and revalidates cache. validationCacheKey is set.
- Page request to Node2 successfully loads index (validIndex is true) and validationCacheKey (validCache is true) so no revalidation occurs. However, the compiled files on Node2 are stale.

### CODE REVIEW

**Comment by IvanChepurnyi** [comment]
Thanks for contribution. Please rebase your original pull request on my latest changes in `develop` branch, so travis automated build should pass.

**Comment by IvanChepurnyi** [comment]
Also there is a problem that unit tests for Layout/Update model will fail after this pull request, as expected cache key structure has changed.

Please update the test case as well:
https://github.com/EcomDev/EcomDev_LayoutCompiler/blob/master/src/app/code/community/EcomDev/LayoutCompilerTest/Test/Model/Layout/UpdateTest.php#L251
https://github.com/EcomDev/EcomDev_LayoutCompiler/blob/master/src/app/code/community/EcomDev/LayoutCompilerTest/Test/Model/Layout/UpdateTest.php#L298
https://github.com/EcomDev/EcomDev_LayoutCompiler/blob/master/src/app/code/community/EcomDev/LayoutCompilerTest/Test/Model/Layout/UpdateTest.php#L303

**Comment by colinmollenhour** [comment]
Thanks for the quick merge! Any chance you will tag a new release soon? Itching to try this on production. :)

Thanks again for your excellent contributions to Magento!

**Comment by IvanChepurnyi** [comment]
Already done:
v1.0.3, and pushed to packagist already.

**Pull request merged**
